### ISSUE TITLE
doesn't work on 0.8.1

### ISSUE THREAD

**Issue by polya20** [combust/mleap-demo#11]
Seems the pyspark and scala notebooks don't work due to changes in the underlying API. The notebooks needs to be fixed to work with the recent versions.

**Comment by ancasarb** [comment]
@polya20 thanks for the note! I've raised a PR combust/mleap-demo#12 to fix some issues with the demos, and once it gets merged, I was able to run the demos alright.

Please let me know if you find any issues, thanks again!

**Comment by ancasarb** [comment]
closing as it's been updated
